database:
  image: mariadb
  environment:
    MYSQL_DATABASE: ifoodCompetition
    MYSQL_USER: ${DB_USERNAME}
    MYSQL_PASSWORD: ${DB_PASSWORD}
    MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  env_file:
    - .env
  restart: always
  ports:
    - "3306:3306"
  volumes:
    - "./dbclient.sh:/dbclient.sh"