database:
  image: mariadb
  environment:
    MYSQL_DATABASE: ifoodCompetition
    MYSQL_USER: ${DB_USERNAME}
    MYSQL_PASSWORD: ${DB_PASSWORD}
    MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  env_file:
    - .env
  restart: always
  command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
  ports:
    - "3306:3306"